services:
  api:
    image: api
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - 8000:80
