version: '3'

services:
  api:
    image: api
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
